version: '3'
services:
  product-service:
    build:
      context: ./product-service
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./product-service/docker/app/.env
    ports:
      - 8092:8080
    depends_on:
      - db
    command: /bin/sh -c 'while ! nc -z db 3307; do sleep 1; done; ./docker/app/bin/init.sh;'
    restart: always
  db:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: micro_root_pass
      MYSQL_DATABASE: micro_db
      MYSQL_USER: micro_user
      MYSQL_PASSWORD: micro_pass
    ports:
      - 3307:3306
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

volumes:
  mariadb-data:    