version: "3"
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: ./deploy/prod.Dockerfile
    image: micro-services_gateway
    env_file:
      - ./gateway/deploy/.env
    ports:
      - 8080:8080
    command: /bin/sh -c '/micro/bin/init.sh'
  
    restart: "no"   
  account-service:
    build:
      context: ./account-service
      args:
        - SSH_PRIVATE_KEY
      dockerfile: ./deploy/prod.Dockerfile
    image: micro-services_account-service
    env_file:
      - ./account-service/deploy/.env
    ports:
      - 8082:8080
    depends_on:
      - db
    command: /bin/sh -c 'while ! nc -z db 3306; do sleep 1; done; /micro/bin/init.sh;'
    restart: always
  product-service:
    build:
      context: ./product-service
      args:
        - SSH_PRIVATE_KEY
      dockerfile: ./deploy/prod.Dockerfile
    image: micro-services_product-service
    env_file:
      - ./product-service/deploy/.env
    ports:
      - 8082:8080
    depends_on:
      - db
    command: /bin/sh -c 'while ! nc -z db 3306; do sleep 1; done; /micro/bin/init.sh;'
    restart: always
  db:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: micro_root_pass
      MYSQL_DATABASE: micro_db
      MYSQL_USER: micro_user
      MYSQL_PASSWORD: micro_pass
    ports:
      - 3307:3306
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
volumes:
  mariadb-data:
