http:
  routers:
    product-rotue:
      rule: "PathPrefix(`/api/v1/`)"
      service: product
  services:
    product:
      loadBalancer:
        servers:
        - url: http://192.168.0.108:8092/
