apiVersion: v1
kind: Service
metadata:
  name: micro-app
  namespace: micro
  labels:
    app: micro-app
spec:
  ports:
  - port: 8001
    targetPort: httpport
    name: http
  selector:
    app: micro-app