apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: micro-env
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30445
  selector:
    app: gateway
