// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	common "github.com/krishnarajvr/micro-common"
	mock "github.com/stretchr/testify/mock"

	model "micro/module/tenant/model"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// Add provides a mock function with given fields: tenant
func (_m *IService) Add(tenant *model.TenantForm) (*model.TenantDto, error) {
	ret := _m.Called(tenant)

	var r0 *model.TenantDto
	if rf, ok := ret.Get(0).(func(*model.TenantForm) *model.TenantDto); ok {
		r0 = rf(tenant)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.TenantForm) error); ok {
		r1 = rf(tenant)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IService) Delete(id int) (*model.TenantDto, error) {
	ret := _m.Called(id)

	var r0 *model.TenantDto
	if rf, ok := ret.Get(0).(func(int) *model.TenantDto); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *IService) Get(id int) (*model.TenantDto, error) {
	ret := _m.Called(id)

	var r0 *model.TenantDto
	if rf, ok := ret.Get(0).(func(int) *model.TenantDto); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: page
func (_m *IService) List(page common.Pagination) (model.TenantDtos, error) {
	ret := _m.Called(page)

	var r0 model.TenantDtos
	if rf, ok := ret.Get(0).(func(common.Pagination) model.TenantDtos); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.TenantDtos)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Pagination) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: form, id
func (_m *IService) Patch(form *model.TenantPatchForm, id int) (*model.TenantDto, error) {
	ret := _m.Called(form, id)

	var r0 *model.TenantDto
	if rf, ok := ret.Get(0).(func(*model.TenantPatchForm, int) *model.TenantDto); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.TenantPatchForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: form, id
func (_m *IService) Update(form *model.TenantForm, id int) (*model.TenantDto, error) {
	ret := _m.Called(form, id)

	var r0 *model.TenantDto
	if rf, ok := ret.Get(0).(func(*model.TenantForm, int) *model.TenantDto); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TenantDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.TenantForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
