// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	common "github.com/krishnarajvr/micro-common"
	mock "github.com/stretchr/testify/mock"

	model "micro/module/tenant/model"
)

// ITenantRepo is an autogenerated mock type for the ITenantRepo type
type ITenantRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: form
func (_m *ITenantRepo) Add(form *model.TenantForm) (*model.Tenant, error) {
	ret := _m.Called(form)

	var r0 *model.Tenant
	if rf, ok := ret.Get(0).(func(*model.TenantForm) *model.Tenant); ok {
		r0 = rf(form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.TenantForm) error); ok {
		r1 = rf(form)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ITenantRepo) Delete(id int) (*model.Tenant, error) {
	ret := _m.Called(id)

	var r0 *model.Tenant
	if rf, ok := ret.Get(0).(func(int) *model.Tenant); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *ITenantRepo) Get(id int) (*model.Tenant, error) {
	ret := _m.Called(id)

	var r0 *model.Tenant
	if rf, ok := ret.Get(0).(func(int) *model.Tenant); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: page
func (_m *ITenantRepo) List(page common.Pagination) (model.Tenants, error) {
	ret := _m.Called(page)

	var r0 model.Tenants
	if rf, ok := ret.Get(0).(func(common.Pagination) model.Tenants); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Tenants)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Pagination) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: form, id
func (_m *ITenantRepo) Patch(form *model.TenantPatchForm, id int) (*model.Tenant, error) {
	ret := _m.Called(form, id)

	var r0 *model.Tenant
	if rf, ok := ret.Get(0).(func(*model.TenantPatchForm, int) *model.Tenant); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.TenantPatchForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: form, id
func (_m *ITenantRepo) Update(form *model.TenantForm, id int) (*model.Tenant, error) {
	ret := _m.Called(form, id)

	var r0 *model.Tenant
	if rf, ok := ret.Get(0).(func(*model.TenantForm, int) *model.Tenant); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tenant)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.TenantForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
