// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	common "github.com/krishnarajvr/micro-common"
	mock "github.com/stretchr/testify/mock"

	model "micro/module/client/model"
)

// IClientRepo is an autogenerated mock type for the IClientRepo type
type IClientRepo struct {
	mock.Mock
}

// AddCredential provides a mock function with given fields: form
func (_m *IClientRepo) AddCredential(form *model.ClientCredential) (*model.ClientCredential, error) {
	ret := _m.Called(form)

	var r0 *model.ClientCredential
	if rf, ok := ret.Get(0).(func(*model.ClientCredential) *model.ClientCredential); ok {
		r0 = rf(form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientCredential)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ClientCredential) error); ok {
		r1 = rf(form)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckCredentials provides a mock function with given fields: form
func (_m *IClientRepo) CheckCredentials(form *model.ClientLoginForm) (*model.ClientCredential, error) {
	ret := _m.Called(form)

	var r0 *model.ClientCredential
	if rf, ok := ret.Get(0).(func(*model.ClientLoginForm) *model.ClientCredential); ok {
		r0 = rf(form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientCredential)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ClientLoginForm) error); ok {
		r1 = rf(form)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClientCredentialRoles provides a mock function with given fields: clientCredentialId
func (_m *IClientRepo) GetClientCredentialRoles(clientCredentialId int) ([]string, error) {
	ret := _m.Called(clientCredentialId)

	var r0 []string
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(clientCredentialId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(clientCredentialId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCredential provides a mock function with given fields: id
func (_m *IClientRepo) GetCredential(id int) (*model.ClientCredential, error) {
	ret := _m.Called(id)

	var r0 *model.ClientCredential
	if rf, ok := ret.Get(0).(func(int) *model.ClientCredential); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientCredential)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCredentials provides a mock function with given fields: page
func (_m *IClientRepo) ListCredentials(page common.Pagination) (model.ClientCredentials, *common.PageResult, error) {
	ret := _m.Called(page)

	var r0 model.ClientCredentials
	if rf, ok := ret.Get(0).(func(common.Pagination) model.ClientCredentials); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ClientCredentials)
		}
	}

	var r1 *common.PageResult
	if rf, ok := ret.Get(1).(func(common.Pagination) *common.PageResult); ok {
		r1 = rf(page)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.PageResult)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(common.Pagination) error); ok {
		r2 = rf(page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PatchCredential provides a mock function with given fields: form, id
func (_m *IClientRepo) PatchCredential(form *model.ClientCredentialPatchForm, id int) (*model.ClientCredential, error) {
	ret := _m.Called(form, id)

	var r0 *model.ClientCredential
	if rf, ok := ret.Get(0).(func(*model.ClientCredentialPatchForm, int) *model.ClientCredential); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClientCredential)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ClientCredentialPatchForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
