// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	common "github.com/krishnarajvr/micro-common"
	mock "github.com/stretchr/testify/mock"

	model "micro/model"
)

// IProductService is an autogenerated mock type for the IProductService type
type IProductService struct {
	mock.Mock
}

// Add provides a mock function with given fields: product
func (_m *IProductService) Add(product *model.ProductForm) (*model.ProductDto, error) {
	ret := _m.Called(product)

	var r0 *model.ProductDto
	if rf, ok := ret.Get(0).(func(*model.ProductForm) *model.ProductDto); ok {
		r0 = rf(product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ProductForm) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IProductService) Delete(id int) (*model.ProductDto, error) {
	ret := _m.Called(id)

	var r0 *model.ProductDto
	if rf, ok := ret.Get(0).(func(int) *model.ProductDto); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *IProductService) Get(id int) (*model.ProductDto, error) {
	ret := _m.Called(id)

	var r0 *model.ProductDto
	if rf, ok := ret.Get(0).(func(int) *model.ProductDto); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: page
func (_m *IProductService) List(page common.Pagination) (model.ProductDtos, error) {
	ret := _m.Called(page)

	var r0 model.ProductDtos
	if rf, ok := ret.Get(0).(func(common.Pagination) model.ProductDtos); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ProductDtos)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Pagination) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: form, id
func (_m *IProductService) Patch(form *model.ProductPatchForm, id int) (*model.ProductDto, error) {
	ret := _m.Called(form, id)

	var r0 *model.ProductDto
	if rf, ok := ret.Get(0).(func(*model.ProductPatchForm, int) *model.ProductDto); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ProductPatchForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: form, id
func (_m *IProductService) Update(form *model.ProductForm, id int) (*model.ProductDto, error) {
	ret := _m.Called(form, id)

	var r0 *model.ProductDto
	if rf, ok := ret.Get(0).(func(*model.ProductForm, int) *model.ProductDto); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ProductForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
