basePath: /v1
definitions:
  common.Error500:
    properties:
      code:
        example: 500
        type: integer
      data:
        type: string
      error:
        example: Internal Server Error
        type: string
    type: object
  dto.UserDto:
    properties:
      created_date:
        type: string
      email:
        example: bob@gmail.com
        type: string
      firstName:
        example: Bob
        type: string
      id:
        example: 1
        type: integer
      name:
        example: bob
        type: string
    type: object
  swagdto.UserResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.UserDto'
        type: array
      error:
        type: object
      status:
        example: 200
        type: integer
    type: object
host: 127.0.0.1:8081
info:
  contact: {}
  description: List APIs of UserManagement Service
  termsOfService: http://swagger.io/terms/
  title: UserManagement Service API Document
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: List all existing users
      parameters:
      - description: Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagdto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/common.Error500'
      summary: List all existing users
      tags:
      - user
swagger: "2.0"
