// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	common "github.com/krishnarajvr/micro-common"
	mock "github.com/stretchr/testify/mock"

	model "micro/model"
)

// IProductRepo is an autogenerated mock type for the IProductRepo type
type IProductRepo struct {
	mock.Mock
}

// Add provides a mock function with given fields: form
func (_m *IProductRepo) Add(form *model.ProductForm) (*model.Product, error) {
	ret := _m.Called(form)

	var r0 *model.Product
	if rf, ok := ret.Get(0).(func(*model.ProductForm) *model.Product); ok {
		r0 = rf(form)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ProductForm) error); ok {
		r1 = rf(form)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *IProductRepo) Delete(id int) (*model.Product, error) {
	ret := _m.Called(id)

	var r0 *model.Product
	if rf, ok := ret.Get(0).(func(int) *model.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *IProductRepo) Get(id int) (*model.Product, error) {
	ret := _m.Called(id)

	var r0 *model.Product
	if rf, ok := ret.Get(0).(func(int) *model.Product); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: page
func (_m *IProductRepo) List(page common.Pagination) (model.Products, error) {
	ret := _m.Called(page)

	var r0 model.Products
	if rf, ok := ret.Get(0).(func(common.Pagination) model.Products); ok {
		r0 = rf(page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Products)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(common.Pagination) error); ok {
		r1 = rf(page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: form, id
func (_m *IProductRepo) Patch(form *model.ProductPatchForm, id int) (*model.Product, error) {
	ret := _m.Called(form, id)

	var r0 *model.Product
	if rf, ok := ret.Get(0).(func(*model.ProductPatchForm, int) *model.Product); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ProductPatchForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: form, id
func (_m *IProductRepo) Update(form *model.ProductForm, id int) (*model.Product, error) {
	ret := _m.Called(form, id)

	var r0 *model.Product
	if rf, ok := ret.Get(0).(func(*model.ProductForm, int) *model.Product); ok {
		r0 = rf(form, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ProductForm, int) error); ok {
		r1 = rf(form, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
